### ISSUE TITLE
An error occurred when entering the existing camera parameters for calculation

### ISSUE THREAD

**Issue by LongHZ140516** [naver/dust3r#117]
Thank you very much for your work. 
I tried to input an existing camera matrix as a known parameter, but I got the following error during the calculation. The matrix before input seems to be fine, but matrix seems to have **NaN** values in the process. 
```
/home/serein/code/dust3r/dust3r/cloud_opt/base_opt.py:175: RuntimeWarning: divide by zero encountered in log
  pose.data[-1] = np.log(float(scale))
mat: tensor([[nan, nan, nan, 0.],
        [nan, nan, nan, 0.],
        [nan, nan, nan, 0.],
        [0., 0., 0., 1.]], device='cuda:0')
Traceback (most recent call last):
  File "/home/serein/code/dust3r/pts_test.py", line 148, in <module>
    loss = scene.compute_global_alignment(init='mst', niter=niter, schedule=schedule, lr=lr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serein/anaconda3/envs/dust3r/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/serein/code/dust3r/dust3r/cloud_opt/base_opt.py", line 306, in compute_global_alignment
    init_fun.init_minimum_spanning_tree(self, niter_PnP=niter_PnP)
  File "/home/serein/anaconda3/envs/dust3r/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/serein/code/dust3r/dust3r/cloud_opt/init_im_poses.py", line 79, in init_minimum_spanning_tree
    return init_from_pts3d(self, pts3d, im_focals, im_poses)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serein/code/dust3r/dust3r/cloud_opt/init_im_poses.py", line 115, in init_from_pts3d
    depth = geotrf(inv(cam2world), pts3d[i])[..., 2]
                   ^^^^^^^^^^^^^^
  File "/home/serein/code/dust3r/dust3r/utils/geometry.py", line 109, in inv
    return torch.linalg.inv(mat)
           ^^^^^^^^^^^^^^^^^^^^^
torch._C._LinAlgError: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.
```

My matrix is ​​calculated by **yaw** and **pitch**, but I don't understand what is wrong.
```
def get_rotation_matrix(yaw, pitch):
    # Convert degrees to radians
    yaw = np.radians(yaw)
    pitch = np.radians(pitch)
    
    # Rotation matrix for yaw (rotation around z axis)
    R_yaw = np.array([
        [np.cos(yaw), -np.sin(yaw), 0],
        [np.sin(yaw), np.cos(yaw), 0],
        [0, 0, 1]
    ])
    
    # Rotation matrix for pitch (rotation around x axis)
    R_pitch = np.array([
        [1, 0, 0],
        [0, np.cos(pitch), -np.sin(pitch)],
        [0, np.sin(pitch), np.cos(pitch)]
    ])
    # Combined rotation matrix
    R = np.dot(R_yaw, R_pitch)
    
    return R
```

**Comment by Munna-Manoj** [comment]
I think your conversion is a little bit off. How about utilizing the existing library to get the R matrix? 
scipy like for Euler to R matrix functionality: 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_euler.html#scipy.spatial.transform.Rotation.from_euler

**Comment by LongHZ140516** [comment]
Thank you very much for your answer.
But I tried to use the `scipy.spatial.transform.Rotation.from_euler` to get the rotation matrix, but still got the same error. I checked the output results of my process and found that some rotation matrices can be calculated normally (the matrix output results of the previous part before the inv calculation are as follows). 
```
mat: tensor([[-0.6882, -0.3427,  0.6395, -0.0314],
        [ 0.5506,  0.3274,  0.7679,  0.0213],
        [-0.4725,  0.8806, -0.0367,  0.0066],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[-0.9959, -0.0654,  0.0626,  0.0303],
        [-0.0367,  0.9238,  0.3812,  0.0360],
        [-0.0827,  0.3773, -0.9224,  0.0560],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[-0.6593, -0.3854,  0.6456, -0.0198],
        [-0.3124,  0.9214,  0.2310, -0.0141],
        [-0.6839, -0.0494, -0.7279, -0.0378],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.0262, -0.5321,  0.8463, -0.0187],
        [ 0.9545,  0.2649,  0.1370,  0.0204],
        [-0.2970,  0.8042,  0.5148,  0.1621],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.9570,  0.0491,  0.2858, -0.4896],
        [-0.0940,  0.9849,  0.1454,  1.6504],
        [-0.2743, -0.1660,  0.9472, -1.4875],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.7096,  0.3728, -0.5979, -0.0032],
        [-0.4890,  0.8715, -0.0370, -0.0072],
        [ 0.5072,  0.3186,  0.8007,  0.0160],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.9998, -0.0119,  0.0142, -0.0092],
        [-0.0012,  0.7266,  0.6870, -0.0083],
        [-0.0185, -0.6869,  0.7265,  0.0176],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.7296,  0.3955, -0.5579,  0.0051],
        [ 0.2626,  0.5912,  0.7626, -0.0339],
        [ 0.6314, -0.7029,  0.3275, -0.0350],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 3.4014e-01,  4.9997e-01, -7.9645e-01,  9.4503e-04],
        [-1.6285e-01,  8.6547e-01,  4.7375e-01, -5.8063e-04],
        [ 9.2617e-01, -3.1438e-02,  3.7580e-01,  2.3255e-02],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]], device='cuda:0')
mat: tensor([[ 7.0442e-01, -3.6666e-01,  6.0774e-01,  5.7846e-04],
        [ 4.9063e-01,  8.7028e-01, -4.3618e-02, -6.2268e-03],
        [-5.1291e-01,  3.2890e-01,  7.9294e-01,  7.3106e-03],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]], device='cuda:0')
mat: tensor([[ 0.6942, -0.4034,  0.5961, -0.0116],
        [-0.3136,  0.5759,  0.7550, -0.0154],
        [-0.6479, -0.7111,  0.2733, -0.0070],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
mat: tensor([[ 0.0505,  0.8524, -0.5205,  1.9347],
        [ 0.1763,  0.5054,  0.8447, -0.5845],
        [ 0.9830, -0.1345, -0.1248, -0.1886],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], device='cuda:0')
/home/serein/code/dust3r/dust3r/cloud_opt/base_opt.py:177: RuntimeWarning: divide by zero encountered in log
  pose.data[-1] = np.log(float(scale))
mat: tensor([[nan, nan, nan, 0.],
        [nan, nan, nan, 0.],
        [nan, nan, nan, 0.],
        [0., 0., 0., 1.]], device='cuda:0')
```
But when input

idx = 12, yaw = -90.0, pitch = -20.9051574478893
pose = [[-1.11022302e-16 1.89183833e-01 9.81941687e-01 0.00000000e+00]
[-1.00000000e+00 1.11022302e-16 -1.11022302e-16 0.00000000e+00]
[-1.11022302e-16 -9.81941687e-01 1.89183833e-01 0.00000000e+00]
[ 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]

In the subsequent calculation, a **nan** value appeared. I don't know why, but the above problem occurs every time in this posture
