### ISSUE TITLE
something wrong in gradio import

### ISSUE THREAD

**Issue by qing-tian-meng-ying** [naver/dust3r#51]
(dust3r) H:\qing\AIproect\dust3r>python demo.py --weights checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth
Traceback (most recent call last):
  File "H:\qing\AIproect\dust3r\demo.py", line 9, in <module>
    import gradio
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "D:\py\anaconda3\envs\dust3r\Lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\py\anaconda3\envs\dust3r\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

**Comment by qing-tian-meng-ying** [comment]
I use conda update gradio to solve this issue, now I can have fun for myself!
